### ISSUE TITLE
Gather rancher-compose config items

### ISSUE THREAD

**Issue by unxs0** [ingadhoc/adhoc-rancher#9]
Need list and brief description of function/spec/requirement of base and odoo stack Rancher catalog configuration items.

**Comment by jjscarafia** [comment]
We should add this items to rancher catalog questions:

- strServerMode: set env variable SERVER_MODE. default empty
- strWorkers or intWorkers: set env variable WORKERS (better if integer validation). Default=0. Required
- strAdminPassword: set env variable ADMIN_PASSWORD. Default 'admin', required

**Comment by unxs0** [comment]
Thx!

**Comment by unxs0** [comment]
Done

**Comment by unxs0** [comment]
WITHOUT_DEMO=false
ADMIN_PASSWORD=admin22
CREATE_DBNAME=production
ODOO_VERSION=9.0
SERVER_MODE=
